const ERROR_CODES = {
    USER_NOT_FOUND: "E001",
    INVALID_PASSWORD: "E002",
    ACCESS_DENIED: "E003",
    INVALID_TOKEN: "E004",
    POST_NOT_FOUND: "E005",
    DATABASE_ERROR: "E006",
  };
  
  module.exports = ERROR_CODES;